package com.dalvikstack.infra.handler;

import fi.iki.elonen.NanoHTTPD;
import org.apache.velocity.VelocityContext;
import com.dalvikstack.infra.router.BaseHandler;

public final class NoJsHandler extends BaseHandler {
    @Override
    protected String getView() { return "nojs"; }

    @Override
    protected void onLoad(VelocityContext ctx, NanoHTTPD.IHTTPSession session) {
        ctx.put("message", "This entire page is generated by the Java backend using Apache Velocity. There is literally zero JavaScript running on this page.");
    }
}
